<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net80</TargetFramework>
    <RootNamespace>space_library</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.21.2" />
    <PackageReference Include="Curiosity.Library" Version="24.8.51133" />
  </ItemGroup>
  
</Project>
